source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               bin/,\
               plugin.xml,\
               templates/,\
               icons/,\
               mik32.png
